### ISSUE TITLE
Front end not updating blocks or payouts

### ISSUE THREAD

**Issue by ylpkm** [216k155/CoiniumServ-PHI1612#1]
![coinium issue](https://user-images.githubusercontent.com/23131453/31579222-ed41a7a0-b0ee-11e7-86a8-17374fff8b86.JPG)
for x11 difficulty is too low, but some blocks found, but no payouts. 
skunk, no blocks found at all
(workers update but blocks do not.

**Comment by 216k155** [comment]
New version released. please check it out
